### PR TITLE
WIP: Read Custom Hotel Port

### PR DESCRIPTION
**Pull request by JSn1nj4**
This PR includes changes to load a custom port set in the user's Hotel config at `~/.hotel.js/conf.json` (`%homepath%\.hotel.js\conf.json` on Windows).

The hotel port is set in `public/preload.js` and added to the `window`.

This PR also includes `ipcRenderer` to try to request the hotelPort from within the `BrowserWindow` object. However, it's possible `ipcRenderer` is unnecessary if the `hotelPort` value is added to the `window` object directly.

Currently neither `window.hotelPort` nor `window.ipcRenderer` are accessible from the client.

----

*Previous discussions on issue #3*

### CODE REVIEW

**Comment by JSn1nj4** [comment]
Some of the commits in this PR were ultimately reverted. There are also some very minor changes made to satisfy the ESLint rules used in the project, but they don't change functionality.

**Comment by macav** [comment]
@JSn1nj4 Thank you! I will look into it towards the end of the week

**Comment by JSn1nj4** [comment]
Thanks! Especially for trying to help an Electron newbie.

**Comment by macav** [comment]
@JSn1nj4 thank you again for your work. It saved me some time and I could use it partially in the latest release. I'm closing this.

**Comment by JSn1nj4** [comment]
Sorry for the late reply. Glad you were able to at least partially use it. Thanks!

**Pull request closed without merging**
